pipeline:
  composer-install:
    image: fpfis/php56-dev
    comands: composer install
  test:
    image: fpfis/php56-dev
    commands: php -l
  run-code:
    image: fpfis/php56-dev
    commands: php index.php
