pipeline:
  composer-install:
    image: fpfis/php56-build
    commands: 
      - composer install 
      
  test:
    image: fpfis/php56-build
    commands: 
      - php -l index.php
    
  run-code:
    image: fpfis/php56-build
    commands: 
      - php index.php
