# Declare a pipeline
pipeline:
  # Declare pipeline step
  composer-install:
    # Use image for step
    image: fpfis/php71-build
    # Run commands from this image
    commands:
      - composer install --ansi

  # Declare another step
  lint-code:
    image: fpfis/php71-build
    commands:
      - php -l /app/build/index.php

  run-code:
    image: fpfis/php71-build
    commands:
      - php /app/build/hello.php 

