version: '2'
services:

  # Define a PHP webserver
  php-webserver:
    # Use a PHP image with apache
    image: fpfis/php56-dev
    # Define settings
    environment:
      - XDEBUG=true
      - DOCUMENT_ROOT=/var/www/html/
    # Mount a local volume in the container
    volumes:
      - ./:/var/www/html/
    # Share the container port with the host
    ports:
      - 8080:8080 

