version: '2'
services:

  # Define a PHP webserver
  php-webserver:
    # Use a PHP image with apache
    image: fpfis/php56-dev
    # We need to force execution in this folder
    working_dir: /app/build/
    command: composer install
    # Define settings
    environment:
      - XDEBUG=true
      - DOCUMENT_ROOT=/app/build
    # Mount a local volume in the container
    volumes:
      - ./:/app/build
    # Share the container port with the host
    ports:
      - 80:8080 

  # Define a mysql service
  mysql:
    image: fpfis/mysql56