version: '2'
services:

  web:
    image: fpfis/php71-dev
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
    environment:
      COMPOSER_MEMORY_LIMIT: "2G"
