version: '2'
services:

  # Define a PHP webserver
  web:
    # Use a PHP image with apache
    image: fpfis/php71-dev
    working_dir: /var/www/html
    # Mount a local volume in the container
    volumes:
      - ./:/var/www/html
    # Share the container port with the host
    ports:
      - 8080:8080

