version: '2'
services:
  # Define a PHP webserver
  php-webserver:
    # Use a PHP image with apache
    image: fpfis/php71
    # Define settings
    environment:
      - XDEBUG=true
      - DOCUMENT_ROOT=/custom71/build   
    # Mount a local volume in the container
    volumes:
      - ./:/custom71/build
    # Share the container port with the host
    ports:
      - 8080:8080
  
  # Define a mysql service
  mysql:
    image: fpfis/mysql56
